version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=654321
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=1
    volumes:
      - /home/nambb/mysqldata:/var/lib/mysql

volumes:
  dbdata:
